version: '3.0'

services:
  notificacions-node:
    image: notificacions-node:latest
    container_name: notifications_mailer
    ports:
      - 3500:3500
    networks:
      - my-network    
    env_file:
      - ./.env

networks:
  my-network:
    external: true
    
